### PR TITLE
Add an OPTIONS response

### PR DESCRIPTION
**Pull request by palewire**
This proposal would add support  OPTIONS request with a simple permissive response. My hope is that this will allow for integration with SSL systems.

For #179. cc @ngbrown

### CODE REVIEW

**Comment by oittaa** [comment]
Would you mind adding a test or few for the OPTIONS method?

**Comment by palewire** [comment]
Sure. Is there an example in the repository now you'd like me to emulate?

**Comment by palewire** [comment]
I believe I have added a test for you, @oitta, but the workflow needs your permission to run.

**Comment by palewire** [comment]
I've made some changes to address issues in the tests and linter.

**Comment by silochad** [comment]
This would be very helpful for our team as well, currently blocked on using this locally due to CORS issues.

**Comment by tbiq** [comment]
> This would be very helpful for our team as well, currently blocked on using this locally due to CORS issues.

Funny seeing you here haha. Literally just ran into this issue with our local dev setup and this is where I came to try and figure it out. 

More generally speaking, anything we can do to help speed up the integration of this feature into the library?

**Comment by palewire** [comment]
I'd love to have somebody test my PR to see if it works for them.

**Comment by tbiq** [comment]
> I'd love to have somebody test my PR to see if it works for them.

Will do! I'll let you know once I've tested things.

**Comment by tbiq** [comment]
Another issue that surfaced during testing is that though you handle the pre-flight OPTIONS request that is the first stage of CORS, you neglected to implement logic into subsequent GET requests that include the `Access-Control-Allow-Origin` header. If you read the COR's documentation here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
you can learn more about this. 

As a test that this fixed things, I added 

```python 
if method == "GET": 
    response['Access-Control-Allow-Origin'] = "*"
```

Right before the return statement in the method `handle` of the `Router` class in `server.py`. Not saying this is the right way to implement the fix, but this did resolve my CORS issues in local testing (after I also made the changes you see in my PR review). 

Curious to hear @oittaa 's perspective on what the right way to implement this would be.

**Comment by bam4564** [comment]
@oittaa bumping this

**Comment by vmg-dev** [comment]
Is there a reason this hasn't been merged?

**Review by oittaa — APPROVED** [review]
lgtm

**Comment by oittaa** [comment]
I haven't had much time following this project, but recently I've updated it to support Python 3.12 and so on. Could you fix the remaining issues?

**Comment by palewire** [comment]
I'm withdrawing this request to tidy up my GitHub task panels. No sweat about it at all.

**Pull request closed without merging**
